name:       sandbox
version:    0.1.0.0
license:    Apache-2.0
author:     Chris Martin
maintainer: ch.martin@gmail.com

dependencies:
  - base
  - text

executables:
  sandbox:
    source-dirs: src
    main: sandbox.hs
